# config.yml

backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
media_folder: 'assets/images/uploads'
site_url: https://rajarv.com
publish_mode: editorial_workflow


collections:
  - name: "posts" # Used in routes, e.g. /admin/collections/blog
    label: "Posts" # Used in the UI
    label_singular: 'Post' # Used in the UI, ie: "New Post" 
    folder: "_posts" # The path to the folder where the documents are stored
    # minimal mistakes pulls title from filename, but netlify pulls from yaml 'title' field
    # so, changing title and previewing it throws 404 error. so comment 'preview_path', then it defaults to home.
    # preview_path: '{{year}}/{{month}}/{{title}}' # it should be equivalent to live site
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template i.e. YYYY-MM-DD-title.md
    editor:
      preview: false
    description: >
      Do not change Publish Date for published posts while updating.
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: 'Publish Date', name: 'date', widget: 'datetime', dateFormat: "YYYY-MM-DD", timeFormat: "HH:mm" }
      - { label: "Update Date", name: 'last_modified_at', widget: 'datetime', dateFormat: "YYYY-MM-DD", timeFormat: "HH:mm"}
      - { label: "Tags", name: 'tags', widget: 'list' }
      - { label: "Categories", name: 'categories', widget: 'list', required: false}
      - { label: "Comments Toggle", name: 'comments', widget: "boolean", default: true}
      - {label: "Body", name: "body", widget: "markdown", hint: 'Main content goes here.'}